# $schema: https://json.schemastore.org/github-workflow.json

name: Check - GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

permissions: {}

jobs:
  zizmor:
    name: Run zizmor
    uses: rbrownwsws/actions-workflows/.github/workflows/check-zizmor.yaml@ca5c8c71a20acc9a44ee007984e7a67447c4f2cf # v1.0.1
    permissions:
      security-events: write  # to upload results to GitHub Advanced Security
