# $schema: https://json.schemastore.org/github-workflow.json

name: Check - GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

permissions: {}

jobs:
  zizmor:
    name: Run zizmor
    uses: rbrownwsws/actions-workflows/.github/workflows/check-zizmor.yaml@c75a4e92d88396a5809f92760b886167030efd03 # v1.0.2
    permissions:
      security-events: write  # to upload results to GitHub Advanced Security
