# $schema: https://json.schemastore.org/github-workflow.json

name: Run release-please

on:
  push:
    branches:
      - master

permissions: {}

jobs:
  release-please:
    name: release-please
    uses: rbrownwsws/actions-workflows/.github/workflows/release-please.yaml@c75a4e92d88396a5809f92760b886167030efd03 # v1.0.2
    with:
      app-client-id: ${{ vars.RELEASE_APP_CLIENT_ID }}
    secrets:
      app-private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
