# $schema: https://json.schemastore.org/github-workflow.json

name: Run release-please

on:
  push:
    branches:
      - master

permissions: {}

jobs:
  release-please:
    name: release-please
    uses: rbrownwsws/actions-workflows/.github/workflows/release-please.yaml@ca5c8c71a20acc9a44ee007984e7a67447c4f2cf # v1.0.1
    with:
      app-client-id: ${{ vars.RELEASE_APP_CLIENT_ID }}
    secrets:
      app-private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
